"use client";
import { useState } from "react";
import { addSlide, createPresentation, exportPptx, updateSlide } from "@/lib/api";
import type { Presentation, Slide } from "@/types/presentation";

export default function Home() {
  const [presentation, setPresentation] = useState<Presentation | null>(null);
  const [selectedSlide, setSelectedSlide] = useState<string | null>(null);
  const [title, setTitle] = useState("Untitled presentation");
  const selected = presentation?.slides.find((slide) => slide.id === selectedSlide);
  async function start() { const created = await createPresentation(title); setPresentation(created); }
  async function createSlide() { if (!presentation) return; const slide = await addSlide(presentation.id); setPresentation({ ...presentation, slides: [...presentation.slides, slide] }); setSelectedSlide(slide.id); }
  async function addElement(type: "text" | "shape") { if (!presentation || !selected) return; const element = type === "text" ? { id: crypto.randomUUID(), type, x: 1, y: 1, width: 5, height: 1, text: "Double-click to edit", font_size: 24, z_index: selected.elements.length } : { id: crypto.randomUUID(), type, x: 1, y: 2.25, width: 3, height: 1.25, shape_type: "round_rect", fill: "#4F46E5", stroke: "#4F46E5", z_index: selected.elements.length }; const updated = await updateSlide(selected.id, { elements: [...selected.elements, element] }); setPresentation({ ...presentation, slides: presentation.slides.map((slide) => slide.id === updated.id ? updated : slide) }); }
  return <main className="min-h-screen bg-slate-100 p-4 text-slate-900"><div className="mx-auto grid max-w-7xl grid-rows-[auto_1fr_auto] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
    <header className="flex items-center justify-between border-b border-slate-200 px-6 py-4"><div><h1 className="font-semibold">Brahma Slides</h1><p className="text-sm text-slate-500">Presentation IR editor foundation</p></div><button disabled={!presentation} onClick={() => presentation && exportPptx(presentation.id)} className="rounded bg-indigo-600 px-4 py-2 text-sm font-medium text-white disabled:cursor-not-allowed disabled:bg-slate-300">Export PPTX</button></header>
    {!presentation ? <section className="grid min-h-[520px] place-items-center p-8"><div className="w-full max-w-md space-y-4 rounded-lg border p-6"><h2 className="text-lg font-semibold">Create a presentation</h2><input aria-label="Presentation title" value={title} onChange={(event) => setTitle(event.target.value)} className="w-full rounded border border-slate-300 px-3 py-2"/><button onClick={start} className="w-full rounded bg-indigo-600 px-4 py-2 text-white">Create presentation</button></div></section> : <section className="grid min-h-[520px] grid-cols-[180px_1fr_220px]">
      <aside className="border-r border-slate-200 p-3"><h2 className="mb-3 text-sm font-semibold uppercase text-slate-500">Slides</h2>{presentation.slides.map((slide, index) => <button key={slide.id} onClick={() => setSelectedSlide(slide.id)} className={`mb-2 w-full rounded p-3 text-left text-sm ${selectedSlide === slide.id ? "bg-indigo-50 text-indigo-800" : "bg-slate-50"}`}>Slide {index + 1}<span className="block text-xs text-slate-400">{slide.elements.length} elements</span></button>)}</aside>
      <div className="grid place-items-center bg-slate-50 p-8"><div className="relative aspect-video w-full max-w-3xl border border-slate-300 shadow" style={{ background: selected?.background ?? "#FFFFFF" }}>{selected ? selected.elements.map((element) => <div key={element.id} className="absolute text-xs" style={{ left: `${(element.x / presentation.dimensions.width) * 100}%`, top: `${(element.y / presentation.dimensions.height) * 100}%` }}>{element.type}</div>) : <p className="grid h-full place-items-center text-slate-400">Add a slide to begin</p>}</div></div>
      <aside className="border-l border-slate-200 p-4"><h2 className="text-sm font-semibold uppercase text-slate-500">Properties</h2><dl className="mt-4 space-y-2 text-sm"><div><dt className="text-slate-500">Title</dt><dd>{presentation.metadata.title}</dd></div><div><dt className="text-slate-500">Selected slide</dt><dd>{selected ? "Slide " + (presentation.slides.indexOf(selected) + 1) : "None"}</dd></div></dl><div className="mt-6 space-y-2"><button disabled={!selected} onClick={() => addElement("text")} className="w-full rounded border border-indigo-200 px-3 py-2 text-sm text-indigo-700 disabled:text-slate-400">Add text</button><button disabled={!selected} onClick={() => addElement("shape")} className="w-full rounded border border-indigo-200 px-3 py-2 text-sm text-indigo-700 disabled:text-slate-400">Add shape</button></div></aside>
    </section>}
    <footer className="flex justify-between border-t border-slate-200 px-6 py-3"><button disabled={!presentation} onClick={createSlide} className="text-sm font-medium text-indigo-700 disabled:text-slate-400">+ Add slide</button><span className="text-sm text-slate-500">{presentation ? `IR version ${presentation.version}` : "No presentation"}</span></footer>
  </div></main>;
}
